#include <iostream>
#include <memory>
#include <string>
#include <cstdlib> // For std::getenv

#include <grpcpp/grpcpp.h>

// These headers are automatically generated by CMake/protoc 
// based on your calculator.proto file.
#include "calculator.grpc.pb.h"

using grpc::Server;
using grpc::ServerBuilder;
using grpc::ServerContext;
using grpc::Status;

// Bring in the generated classes from the 'calculator' package defined in your proto
using calculator::CalculatorService;
using calculator::MultiplyRequest;
using calculator::MultiplyResponse;

// =============================================================================
// 1. Service Implementation
// =============================================================================
// This class implements the actual logic of your gRPC service.
class CalculatorServiceImpl final : public CalculatorService::Service {
    
    // Override the Multiply RPC method defined in the proto file
    Status Multiply(ServerContext* context, const MultiplyRequest* request, MultiplyResponse* reply) override {
        
        // Extract the inputs 'a' and 'b' from the request payload
        int32_t a = request->a();
        int32_t b = request->b();
        
        std::cout << "Received request to multiply: " << a << " * " << b << std::endl;
        
        // Perform the calculation
        int32_t result = a * b;
        
        // Set the result in the response payload
        reply->set_result(result);
        
        // Return OK to let the client know the RPC was successful
        return Status::OK;
    }
};

// =============================================================================
// 2. Server Bootstrapping
// =============================================================================
void RunServer() {
    // Cloud Run injects a PORT environment variable. We must listen on this port.
    // If it's not set (like in local development), we default to 50051.
    std::string port = "50051";
    if (const char* env_p = std::getenv("PORT")) {
        port = env_p;
    }
    
    // Bind to 0.0.0.0 so the container can receive outside traffic
    std::string server_address("0.0.0.0:" + port);
    
    CalculatorServiceImpl service;

    ServerBuilder builder;
    
    // Listen on the given address without any authentication mechanism.
    // (In Cloud Run, GCP's IAM handles the security layer for internal traffic)
    builder.AddListeningPort(server_address, grpc::InsecureServerCredentials());
    
    // Register our service implementation
    builder.RegisterService(&service);
    
    // Assemble the server
    std::unique_ptr<Server> server(builder.BuildAndStart());
    std::cout << "Server listening on " << server_address << std::endl;
    
    // Keep the server running until the process is killed
    server->Wait();
}

int main(int argc, char** argv) {
    RunServer();
    return 0;
}
