#include <iostream>
#include <memory>
#include <string>
#include <cstdlib> // for std::getenv
#include <chrono> // for time measurement

#include "../include/baccarat_table.h"
#include "../include/baccarat_defs.h"

#include <grpcpp/grpcpp.h>

// These headers are automatically generated by CMake/protoc 
// based on your calculator.proto file.
#include "calculator.grpc.pb.h"
#include "baccaratSim.grpc.pb.h"

using grpc::Server;
using grpc::ServerBuilder;
using grpc::ServerContext;
using grpc::Status;

// Bring in the generated classes from the 'calculator' package defined in your proto
using calculator::CalculatorService;
using calculator::MultiplyRequest;
using calculator::MultiplyResponse;

// =============================================================================
// Calculator Service Implementation
// =============================================================================
// This class implements the actual logic of your gRPC service.
class CalculatorServiceImpl final : public CalculatorService::Service {

  // Override the Multiply RPC method defined in the proto file
  Status Multiply(ServerContext* context, const MultiplyRequest* request, MultiplyResponse* reply) override {

    // Extract the inputs 'a' and 'b' from the request payload
    int32_t a = request->a();
    int32_t b = request->b();

    std::cout << "Received request to multiply: " << a << " * " << b << std::endl;

    // Perform the calculation
    int32_t result = a * b;

    // Set the result in the response payload
    reply->set_result(result);

    // Return OK to let the client know the RPC was successful
    return Status::OK;
  }
};

// =============================================================================
// Baccarat Simulator Service
// =============================================================================
// Note: This assumes your baccaratSim.proto defines a service named "BaccaratEngine" 
// inside a package named "baccaratSim"
class BaccaratSimServiceImpl final : public baccaratSim::BaccaratEngine::Service {
  Status SimulateBaccarat(ServerContext* context, const baccaratSim::SimRequest* request, baccaratSim::SimResponse* reply) override {
    int hands_to_play = request->number_of_hands();
    std::cout << "Simulating " << hands_to_play << " hands..." << std::endl;

    // C++ simulation loop goes here
    Baccarat_table table;
    Round_Record round;
    Baccarat_Outcome outcome;

    int banker_wins = 0;
    int player_wins = 0;
    int tie_wins = 0;
    int panda_wins = 0;
    int dragon_wins = 0;

    //start time here
    auto start_time = std::chrono::steady_clock::now();

    for(int i = 0; i < hands_to_play; i++)
    {
      round = table.play_round();
      outcome = round.winner;
      switch (outcome)
      {
        case(Baccarat_Outcome::BANKER):
          banker_wins++;
          break;
        case(Baccarat_Outcome::PLAYER):
          player_wins++;
          break;
        case(Baccarat_Outcome::TIE):
          tie_wins++;
          break;
        case(Baccarat_Outcome::PANDA):
          panda_wins++;
          break;
        case(Baccarat_Outcome::DRAGON):
          dragon_wins++;
          break;
      }
    }
    //end time here
    auto end_time = std::chrono::steady_clock::now();

    auto duration = std::chrono::duration_cast<std::chrono::milliseconds>(end_time - start_time);
    int execution_time = duration.count();

    reply->set_banker_wins(banker_wins);
    reply->set_player_wins(player_wins);
    reply->set_ties(tie_wins);
    reply->set_pandas(panda_wins);
    reply->set_dragons(dragon_wins);
    reply->set_execution_time_ms(execution_time);

    return Status::OK;
  }
};

// =============================================================================
// 2. Server Bootstrapping
// =============================================================================
void RunServer() {
  // Cloud Run injects a PORT environment variable. We must listen on this port.
  // If it's not set (like in local development), we default to 50051.
  std::string port = "50051";
  if (const char* env_p = std::getenv("PORT")) {
    port = env_p;
  }

  // Bind to 0.0.0.0 so the container can receive outside traffic
  std::string server_address("0.0.0.0:" + port);

  CalculatorServiceImpl calculator_service;
  BaccaratSimServiceImpl baccarat_service;

  ServerBuilder builder;

  // Listen on the given address without any authentication mechanism.
  // (In Cloud Run, GCP's IAM handles the security layer for internal traffic)
  builder.AddListeningPort(server_address, grpc::InsecureServerCredentials());

  // Register our service implementation
  builder.RegisterService(&calculator_service);
  builder.RegisterService(&baccarat_service);

  // Assemble the server
  std::unique_ptr<Server> server(builder.BuildAndStart());
  std::cout << "Server listening on " << server_address << std::endl;

  // Keep the server running until the process is killed
  server->Wait();
}

int main(int argc, char** argv) {
  RunServer();
  return 0;
}
