# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from . import baccaratSim_pb2 as baccaratSim__pb2

GRPC_GENERATED_VERSION = '1.80.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in baccaratSim_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class BaccaratEngineStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.SimulateBaccarat = channel.unary_unary(
                '/baccaratSim.BaccaratEngine/SimulateBaccarat',
                request_serializer=baccaratSim__pb2.SimRequest.SerializeToString,
                response_deserializer=baccaratSim__pb2.SimResponse.FromString,
                _registered_method=True)


class BaccaratEngineServicer(object):
    """Missing associated documentation comment in .proto file."""

    def SimulateBaccarat(self, request, context):
        """Unary RPC
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_BaccaratEngineServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'SimulateBaccarat': grpc.unary_unary_rpc_method_handler(
                    servicer.SimulateBaccarat,
                    request_deserializer=baccaratSim__pb2.SimRequest.FromString,
                    response_serializer=baccaratSim__pb2.SimResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'baccaratSim.BaccaratEngine', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('baccaratSim.BaccaratEngine', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class BaccaratEngine(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def SimulateBaccarat(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/baccaratSim.BaccaratEngine/SimulateBaccarat',
            baccaratSim__pb2.SimRequest.SerializeToString,
            baccaratSim__pb2.SimResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
