# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: text_processor.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'text_processor.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x14text_processor.proto\x12\x0etext_processor\"!\n\x0bTextRequest\x12\x12\n\ninput_text\x18\x01 \x01(\t\"#\n\x0cTextResponse\x12\x13\n\x0boutput_text\x18\x01 \x01(\t2Y\n\x0bTextService\x12J\n\x0bProcessText\x12\x1b.text_processor.TextRequest\x1a\x1c.text_processor.TextResponse\"\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'text_processor_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_TEXTREQUEST']._serialized_start=40
  _globals['_TEXTREQUEST']._serialized_end=73
  _globals['_TEXTRESPONSE']._serialized_start=75
  _globals['_TEXTRESPONSE']._serialized_end=110
  _globals['_TEXTSERVICE']._serialized_start=112
  _globals['_TEXTSERVICE']._serialized_end=201
# @@protoc_insertion_point(module_scope)
