# Generated by Django 6.0.4 on 2026-04-13 22:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='inSiteProject',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='project',
            name='slug',
            field=models.SlugField(blank=True, max_length=200),
        ),
    ]
